#-*- restclient -*-
# eval these in your environment
# (defvar akey "1555b35654ad1656d804")
# (defvar skey "h7GhxuBLTrlhVUyxSPUKUV8r/2EI4ngqJxD7iBdBYLhwluN30JaT3Q==")

# Get the current realm
:date := (setq time-now (s3--format-date))
:path := (setq path "admin/realm/period")
:s3-auth := (s3auth path "GET" akey skey nil nil time-now)
GET http://127.0.0.1:8001/:path
authorization: :s3-auth
Date: :date

