#-*- restclient -*-
# eval these in your environment
# (setq akey "6USFJP335ZEE1O886EEM")
# (setq skey "9Og2LTLM40Tht2Aqvk19H7akvANpRNAAERuma3Yr")

# Get the current realm
:date := (setq time-now (s3--format-date))
:path := (setq path "admin/realm/period")
:s3-auth := (s3auth path "GET" akey skey nil nil time-now)
GET http://127.0.0.1:8001/:path
authorization: :s3-auth
Date: :date

# Create a user
:date := (setq time-now (s3--format-date))
:path := (setq path "admin/user")
:s3-auth := (s3auth path "PUT" akey skey nil nil time-now)
PUT http://127.0.0.1:8001/:path
authorization: :s3-auth
Date: :date
Content-Type : application/json

{
  "uid":"foo"
  "display-name":"Foo User"
}
